{"uuid": "bed9b8af-5da3-4684-bb04-03213ea53470", "children": ["64769bd2-3605-467c-82fa-fa10b8daf74c"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:1910\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:1910\n    at JWProxy.command (/Users/pbox/headspinio-pboxagent/appium/1.17.0/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:266:13)\n", "trace": "  File \"/home/headspin/.local/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/headspin/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/headspin/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/headspin/Documents/maps/io/headspin/maps/conftest.py\", line 51, in driver\n    r = driver.session\n  File \"/home/headspin/.local/lib/python3.8/site-packages/appium/webdriver/extensions/session.py\", line 41, in session\n    return self.execute(Command.GET_SESSION)['value']\n  File \"/home/headspin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"/home/headspin/.local/lib/python3.8/site-packages/appium/webdriver/errorhandler.py\", line 31, in check_response\n    raise wde\n  File \"/home/headspin/.local/lib/python3.8/site-packages/appium/webdriver/errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"/home/headspin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1644222663798, "stop": 1644222709297}], "start": 1644222663798, "stop": 1644222709415}